
services:
  app:
    container_name: portfolio-container
    build:
      context: .
      dockerfile: Dockerfile.mounted
    ports:
      - "3000:3000"  # Mapea puerto 3000 (host) → 3000 (contenedor)
    volumes:
      - .:/app
      - /app/node_modules  # Para evitar conflictos con node_modules local
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
    external: true