# Usamos Node.js con Alpine para un entorno ligero
FROM node:20-alpine

# Upgrade system packages to fix vulnerabilities
RUN apk update && apk upgrade

# Establece el directorio de trabajo
WORKDIR /app

COPY package*.json ./

RUN npm install

# COPY . .

# EXPOSE 3000

# Comando por defecto (modo desarrollo)
CMD ["npm", "run", "dev"]

# CMD ["npm", "run", "dev", "--", "--hostname", "0.0.0.0"]